language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "node"
before_install:
  - npm i -g npm
before_script:
  - npm install -g gulp-cli
script: npm test
cache:
  apt: true
  directories:
  - "$HOME/.npm"
